language: cpp
before_script:
- wget https://github.com/libimobiledevice-win32/libplist/releases/download/1.12-gcc/libplist.tar.gz
- mkdir $HOME/ext
- tar -xvzf libplist.tar.gz -C $HOME/ext
script:
- export CFLAGS=-I$HOME/ext/include
- export PKG_CONFIG_PATH=$HOME/ext/lib/pkgconfig:$PKG_CONFIG_PATH
- export LDFLAGS=-L$HOME/ext/lib
- "./autogen.sh"
- "./configure --prefix=$HOME/out"
- make
after_success:
- make install
- tar -zcvf libusbmuxd.tar.gz -C $HOME/out .
deploy:
  provider: releases
  file: libusbmuxd.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: J5bFm/rXpI8Z5s3H+GgMQmhsexcLZPLhQqsFyOKDhsvGrVj2ZAZ2iUDxiyV33i+PoJwnpBBOexk9vtcd5L5AdcH+TRtXTuk4ovsul0QqZGnYzzBYi3MDIp7LuJnFVn4vfCzIecPlxv6gNLEp6MW0ispNRwAEcgV2VUcY91X09HA=